version: '3.9'

services:
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
    volumes:
      - database:/var/lib/mysql
      - ./database-init.sql:/docker-entrypoint-initdb.d/database-init.sql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: root1234

volumes:
  database:
